# Generated by Django 6.1.1 on 2026-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
