# Generated by Django 6.1.1 on 2026-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_reported_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
